### ISSUE TITLE
double licenses in "--exclude"

### ISSUE THREAD

**Issue by teemgreen** [davglass/license-checker#103]
"--exclude" works with single licenses:
license-checker --exclude 'MIT, MIT/X11, BSD, ISC'

Is it possible to add double licenses (licenses: ['MIT', 'BSD'])?
for example: license-checker --exclude '[MIT, BSD], ISC'

**Comment by davglass** [comment]
Not in it's current form no. Not sure why you would want to filter that way any way. Can you explain the use case for this?

**Comment by dancrumb** [comment]
I think PR #109 address this, right?

**Comment by davglass** [comment]
Good call, this should cover it..
