### ISSUE TITLE
Licenses field strange behavior after updating 11 -> 13.0.1

### ISSUE THREAD

**Issue by klimashkin** [davglass/license-checker#114]
<img width="1109" alt="screen shot 2017-07-17 at 7 37 51 pm" src="https://user-images.githubusercontent.com/576077/28298324-7acde7ae-6b27-11e7-94f0-6b699c8bf4d5.png">
Which doesn't make much sense

**Comment by davglass** [comment]
Sorry about that, pushed a fix in `license-checker@13.0.2`.

**Comment by klimashkin** [comment]
Thanks!
