### ISSUE TITLE
Why does lib/license.js not use \b for the beginning as well?

### ISSUE THREAD

**Issue by neverendingqs** [davglass/license-checker#123]
In https://github.com/davglass/license-checker/blob/master/lib/license.js?r=f58b20c, only `\b` is used at the end of:

```javascript
var MIT = /MIT\b/;
var BSD = /BSD\b/;
var ISC = /ISC\b/;
...
var APACHE = /Apache License\b/;
var WTFPL = /WTFPL\b/;
```

Why not the beginning as well, to match the exact term?

For example, `/MIT\b/` would match `SUBMIT`, while `/\bMIT\b/` would not.

**Comment by davglass** [comment]
That's a good question ;)

I think I never updated those when I added the spdx and the `MIT_LICENSE` checks. It was just a fall back to afterward. I could add the `\b` before them as well. A PR for that would be awesome ;)
