### ISSUE TITLE
Automate npm publishing

### ISSUE THREAD

**Issue by neverendingqs** [davglass/license-checker#127]
For your consideration: https://docs.travis-ci.com/user/deployment/npm/

Travis CI can automatically publish npm packages for you based on git tags. I noticed you publish fairly frequently, so this should make life easier for you.

Here's an example of how the `.travis.yml` file looks like with this feature: https://github.com/neverendingqs-sandbox/nodejs-lib-example/blob/master/.travis.yml

Feel free to ignore this - just wanted to get this in your radar in case you haven't considered it before.

**Comment by davglass** [comment]
Yes, I'm fully aware of how to handle this. I never use this as I would rather control the updates myself. Thanks for the info tho..
