### ISSUE TITLE
whitelist licenses to not fail on

### ISSUE THREAD

**Issue by tknerr** [davglass/license-checker#128]
Currently you can only blacklist licenses via `-failOn`

However, if you want to be more strict you probably want to explicitly whitelist the licenses which are ok for you.

Ideas:

 * introduce a negation operator, e.g.: `-failOn="!(MIT,Apache)"` 
 * introduce another flag, e.g.: `-notFailOn="MIT,Apache"`

**Comment by developius** [comment]
This would be really useful for a CI pipeline when checking if a commit introduces policy-breaking licensed code. 👍

**Comment by davglass** [comment]
Pushed in `license-checker@16.0.0`

**Comment by tknerr** [comment]
@davglass awesome, thanks!

**Comment by developius** [comment]
Sweet! Thanks! Works nicely in my CI pipeline 💯

**Comment by bufferoverflow** [comment]
a fantastic feature, thank you!

**Comment by davglass** [comment]
It's not exactly perfect yet and you may have some issues. That code just does an [`indexOf`](https://github.com/davglass/license-checker/blob/master/lib/index.js#L319) check when it should actually be doing an [`spdx`](https://github.com/davglass/license-checker/blob/master/lib/index.js#L359-L367) check like it does in other places. This will require some major changes and I didn't have time to do that :(

**Comment by developius** [comment]
@davglass funnily enough, I just ran into that issue. One of my sub-dependencies (`jsonify`, which is depended on by `sendgrid`) has a license field of `"Public Domain"` which I'm guessing is breaking the `indexOf`. Not a biggie, but would be a useful fix in the future.
