### ISSUE TITLE
license-checker license clarification

### ISSUE THREAD

**Issue by urish** [davglass/license-checker#129]
Hi, first of all - thank you for creating this great tool!

While the [package.json](https://github.com/davglass/license-checker/blob/a9bd001b649bfa186bae5598bb8c67ff56383599/package.json#L92) specifies a BSD-3-Clause license, the [LICENSE](https://github.com/davglass/license-checker/blob/a9bd001b649bfa186bae5598bb8c67ff56383599/LICENSE#L2) file adds "All rights reserved", which is not a part of the BSD-3-Clause license, and which can be interpreted as "Yahoo reserves all its rights for the code under the copyright law, and does not grant any rights", contradicting the BSD-3-Clause license that follows.

Can you please clarify this?

**Comment by davglass** [comment]
This was actually just a very old license file (dated 2012), I've updated it with the proper one.

**Comment by urish** [comment]
Thank you very much!
