### ISSUE TITLE
asFiles does not handle scoped packages

### ISSUE THREAD

**Issue by lambourn** [davglass/license-checker#132]
[`asFiles`](https://github.com/davglass/license-checker/blob/master/lib/index.js#L543) errors if the package.json contains scoped packages, e.g. in my case
```
"dependencies": {
  "@angular/animations": "~4.2.0"
}
```
the `moduleName` evaluates to `"@angular/animations@4.2.6"` and the `outFileName` to `"angular/animations4.2.6-LICENSE.txt"` respectively. 

As the `angular` subfolder in the `outDir` does not get generated I end up getting this error:

`Error: ENOENT: no such file or directory, open 'output/angular/animations4.2.6-LICENSE.txt'`

**Comment by davglass** [comment]
Fixed in `license-checker@16.0.0`
