### ISSUE TITLE
Provide copyright notices

### ISSUE THREAD

**Issue by honzajavorek** [davglass/license-checker#154]
I use the license checker to walk through the dependencies tree and to figure out three properties of all dependencies:

- license name
- full license text
- [copyright notice](https://en.wikipedia.org/wiki/Copyright_notice)

The last one is not provided out of the box, so I'm wrapping the `license-checker` into a custom script to somehow parse out the copyright notice from the license text if it exists at all. When it does not exist, I at least pick up the `author` property from `package.json`.

I think this is something the `license-checker` could do itself. I would be willing to work on implementing this, but would like to hear from maintainers and other users what they think first.

**Comment by honzajavorek** [comment]
Just to add, the copyright notice is important as it plays an important role in attributing (related to https://github.com/davglass/license-checker/issues/51).

**Comment by zodiac403** [comment]
Hi @honzajavorek 
do you want to take a loot at PR #156 (merged last week)? Probably this solves your issue.

**Comment by honzajavorek** [comment]
@zodiac403 I only scanned the PR, looks great! I'll try to do some actual work on top of it, then let's see. If it doesn't satisfy my needs, I'll either re-open this or file specific issues/PRs.
