### ISSUE TITLE
failOn and onlyAllow -vs- exclude

### ISSUE THREAD

**Issue by codepunkt** [davglass/license-checker#168]
Both `failOn` and `onlyAllow` accept a semicolon-separated list and explicitely warn about passing a comma-separated list because license identifiers might include commas.

`exclude` on the other hand accepts a comma-separated list.

This is unintuitive. I would assume the same parsing logic behind all of these. If this is different, it might also explain #167.

**Comment by mischah** [comment]
Duplicates #159
