### ISSUE TITLE
JSON uses single quotes instead of double quotes, and therefore isn't valid JSON

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [davglass/license-checker#170]
Hello,

It looks like when running license-checker with the `--json` flag, the JSON that's generated uses single quotes instead of double quotes, which means that parsing it with JSON.parse() fails.

**Comment by davglass** [comment]
I'm not sure how that's possible, we just use the built in `JSON.stringify` and print it to the console:
https://github.com/davglass/license-checker/blob/master/bin/license-checker#L75

**Comment by davglass** [comment]
ok, the `json` that is in that callback is an actual Javascript `Object`. You don't need to parse it or eval it, it's already an object.

**Comment by Bosch-Eli-Black** [comment]
Ah, you're right!

Thanks for the help :)

If `json` is really an object, do you think it would make sense to rename it to something else, like `packages`? To me, JSON makes it sound like it's a JSON string.

**Comment by davglass** [comment]
Fixed in 231bd3f2412507be1d702ad100b23c1b1fe93602

**Comment by Bosch-Eli-Black** [comment]
Thanks, man :)
