### ISSUE TITLE
MIT versus MIT* - semantics of --unknown

### ISSUE THREAD

**Issue by mwittig** [davglass/license-checker#29]
I am wondering what the semantics of the --unknown option is. Please clarify.

Take the detection of MIT licenses, for example, where
- MIT is output, if the MIT string was found as part of the license (or licenses) descriptor property, and
- MIT* is output if the aforementioned properties do not exist and some text pattern of the license clause is found in the ReadMe or License file of the module source.

Using option --unknown highlights the MIT markings as unknown licenses while it does not show the MIT* ones . Why do you consider, the text pattern matching as more accurate over content of the of the license or licenses descriptor properties? Shouldn't this be the other way round? I assume this is a bug.

If I am wrong and this is a feature you could perhaps combine the two methods of license checking for the case where the descriptor contains the license or licenses property.

**Comment by davglass** [comment]
Can you give me a repro case? There is only one if block that get's executed when the `unknown` option is present. If the license is guessed, it is removed from the list.

**Comment by mwittig** [comment]
Take the following package descriptor and perform npm install:
{
  "name": "test-app",
  "version": "0.0.1",
  "dependencies": {
    "normalize-package-data": "^1.0.3"
  }
}

Now run license-checker. This will give you the following output:
├─ github-url-from-git@1.4.0
│  ├─ licenses: MIT
│  └─ repository: https://github.com/visionmedia/node-github-url-from-git
├─ github-url-from-username-repo@1.0.2
│  ├─ licenses: BSD-2-Clause
│  └─ repository: https://github.com/robertkowalski/github-url-from-username-repo
├─ normalize-package-data@1.0.3
│  ├─ licenses: BSD*
│  └─ repository: git://github.com/meryn/normalize-package-data
├─ semver@4.2.0
│  ├─ licenses: BSD
│  └─ repository: git://github.com/isaacs/node-semver
└─ test-app@0.0.4
   └─ licenses: UNKNOWN

Now run license-checker --unknwon. This will give you the following output:
├─ github-url-from-git@1.4.0
│  ├─ licenses: MIT
│  └─ repository: https://github.com/visionmedia/node-github-url-from-git
├─ github-url-from-username-repo@1.0.2
│  ├─ licenses: BSD-2-Clause
│  └─ repository: https://github.com/robertkowalski/github-url-from-username-repo
├─ semver@4.2.0
│  ├─ licenses: BSD
│  └─ repository: git://github.com/isaacs/node-semver
└─ test-app@0.0.4
   └─ licenses: UNKNOWN

However, this looks wrong to me. I would have expected two entries, namely the unknown license for test-app and the BSD* for normalize-package-data.

**Comment by davglass** [comment]
This should behave as you expect now in `license-checker@2.0.1`

**Comment by mwittig** [comment]
Thank you very much for covering this. With the new version I get the following results for the test case outlined earlier:

C:\Users\marcus\Documents\Devel>license-checker.cmd  --unknown
scanning C:\Users\marcus\Documents\Devel
├─ github-url-from-git@1.4.0
│  ├─ licenses: MIT
│  └─ repository: https://github.com/visionmedia/node-github-url-from-git
├─ github-url-from-username-repo@1.0.2
│  ├─ licenses: BSD-2-Clause
│  └─ repository: https://github.com/robertkowalski/github-url-from-username-repo
├─ normalize-package-data@1.0.3
│  ├─ licenses: UNKNOWN
│  └─ repository: git://github.com/meryn/normalize-package-data
├─ semver@4.2.0
│  ├─ licenses: BSD
│  └─ repository: git://github.com/isaacs/node-semver
└─ test-app@0.0.1
   └─ licenses: UNKNOWN

I'd have rather expected just two entries output for "normalize-package-data" and "test-app" rather than all entries, and I was a bit surprised to see you've changed "BSD*" to "unknown" in the output. Well, I am not saying this wrong and the solution you have provided with 2.01 is just fine for me. I just thought that this might also confuse other users.
