### ISSUE TITLE
Bug: Normalization of git URLs (moduleInfo.repository) does not work as intended

### ISSUE THREAD

**Issue by mwittig** [davglass/license-checker#30]
Sorry, I am not able to create a fork & pull request at the moment.

The Normalization of git URLs (moduleInfo.repository) in index.js, line 40 and following does not work as intended. 

40:     moduleInfo.repository = json.repository.url.replace('git://github.com', 'https://github.com').replace('.git', '');
41:    moduleInfo.repository = json.repository.url.replace('git@github.com:', 'https://github.com/').replace('.git', '');

The assignment in line 40 has no effect as it is overwritten by the assignment in line 41. Suggested Fix: 

Change line 41 as follows:
            moduleInfo.repository = moduleInfo.repository.replace('git@github.com:', 'https://github.com/').replace('.git', '');

**Comment by davglass** [comment]
Published in `license-checker@2.0.2`
