### ISSUE TITLE
Expose path to license file

### ISSUE THREAD

**Issue by davej** [davglass/license-checker#31]
Would it be possible to also expose the path to the license file (where available) in the output?

**Comment by davglass** [comment]
I could add that, but that would only help when we actually have to parse the license file. Most of the time we just grab the data from the `license` key in the `package.json` and only fall back to flat files when needed. From my experience there are far fewer modules with actual license files than there are with just the data in the `package.json` or the `README.md`.

**Comment by davej** [comment]
Ah ok. Would you consider switching around the order so that it checks the flat files first and the fallbacks to `package.json`?

If there is a LICENSE file in the repo then I think it should probably take priority over what is specified in the package.json since it is more explicit. From a legal point of view (admittedly only one potential use-case of this module) the license key in `package.json` doesn't really mean anything by itself.

Thoughts?

**Comment by davglass** [comment]
Yeah, I could probably do that.. I'll take a look when I can.

**Comment by davglass** [comment]
I reorganized some of the code and have it add a `licenseFile` property to the output. Landed it in fde9635, care to give it a spin?

The only thing I did change was that if we find the license in the `package.json` first, we don't parse the license file. Parsing the file is harder than it should be so I didn't want any false positives. And it broke the current tests :)

**Comment by davej** [comment]
Cool, I'll give it a spin tomorrow.

Just to give a bit of background, I'm essentially looking for a replacement for https://github.com/benbalter/licensee (check out 'The solution' section in the README file) but without the dependencies on Ruby and without the requirement for each repo to be a git repo.

**Comment by davej** [comment]
I'm not suggesting that you should implement what they're doing by the way, just wanted to give a bit of background. [Github are also using Licensee](https://github.com/blog/1964-open-source-license-usage-on-github-com).

**Comment by davej** [comment]
Excellent! Works very well in my testing.

**Comment by davglass** [comment]
Published in `license-checker@3.0.0`
