### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by garthk** [davglass/license-checker#33]
Failure in `lib/index.js:70` if `json.path` is `undefined`:

```js
    files = fs.readdirSync(json.path).filter(function(filename) {
        filename = filename.toUpperCase();
        return filename.indexOf('LICENSE') > -1 || filename.indexOf('LICENCE') > -1 ;
    });
```

You're also failing to check `err` when `read` calls back around line 115, but that's not the cause this time.

**Comment by davglass** [comment]
Pushed in `license-checker@3.0.1`
