### ISSUE TITLE
Feature: Add Error handling on initialize

### ISSUE THREAD

**Issue by ptusch** [davglass/license-checker#44]
Hi,

I think the project could benefit from a nice error reporting.
To keep compatibility to dependents, I can't think of a totally nice solution but I think I have something that will allow a dependent package to have easy error checking (not check for undefined@undefined).

In the `init` function, we could simply return an error whenever read fails.
The callback could just return the error like this:
`callback(sorted, err)`

Any thoughts on this?

**Comment by davglass** [comment]
Closing this as you added this in 1a93a41569a53a1580c94c2c903a5bc127ad2692
