### ISSUE TITLE
Feature: verbose output

### ISSUE THREAD

**Issue by ptusch** [davglass/license-checker#46]
I think a verbose argument should be set to allow a user to simply see what's going on.
The 'scanning pathXY' is not used in external libraries and really looks odd in tests.

Verbosing should be either on or off.
Since chalk is already included, proper coloring is possible, too!

Any thoughts on this?

**Comment by davglass** [comment]
Agreed, we should include the `debug` module and then have the flags determine what is shown.

**Comment by swashcap** [comment]
This would be really nice. The output is coming [from a `console.error` call](https://github.com/davglass/license-checker/blob/3583d925e96fc9f63b3bbf0110b11c8448aed0e7/lib/index.js#L144), which is getting written to stderr.

**Comment by davglass** [comment]
Closing as #53 handles this.
