### ISSUE TITLE
dependencies vs devDependencies flag

### ISSUE THREAD

**Issue by claycephas** [davglass/license-checker#52]
Please add a flag to output licenses for dependencies, devDependencies, or both.

**Comment by davglass** [comment]
This wouldn't be too hard to add in, this line is all that would be changed:
https://github.com/davglass/license-checker/blob/master/lib/index.js#L150

**Comment by delenius** [comment]
+1 for this feature request.

Strangely enough, changing that "dev" field to false (or removing it) has no effect on the output. At least when I run it on license-checked itself, it produces the same number of lines.

**Comment by davglass** [comment]
Pushed in `license-checker@5.0.0`

**Comment by davglass** [comment]
You can now use `--production` to limit to only production dependencies and `--development` to limit to only development dependencies.

**Comment by delenius** [comment]
Thanks! :+1:
