### ISSUE TITLE
LGPL and GPL Licenses

### ISSUE THREAD

**Issue by mischah** [davglass/license-checker#60]
Hej, thanks for this awesome module.

I wonder if you would accept a simple pull request for adding LGPL and GPL Licenses to [lib/license.js](https://github.com/davglass/license-checker/blob/master/lib/license.js) since there is #50 in the making?

**Comment by davglass** [comment]
Sure, I welcome almost all Pull Requests :)

**Comment by mischah** [comment]
Thanks. PR will land pretty soon :octocat:
