### ISSUE TITLE
Dependency graph for each module

### ISSUE THREAD

**Issue by hpurmann** [davglass/license-checker#63]
We want to use this library for checking each of our dependencies and matching them with a whitelist.

If one of the dependencies has a non-whitelisted license, we want to fail a test and give useful information, which module failed and where the module comes from.

The first idea was to use the `dependencyPath` property. [Since npm 3 though](https://docs.npmjs.com/how-npm-works/npm3), this path does not necessarily fit the modules dependency. On file level, the dependency could be in the root `node_modules` folder but not being a direct dependency of the project.

Instead of using `read-installed`, traversing over the result and thus generating such results ourselves, we thought about creating a PR to let `license-checker` generate this information.

How likely is it you would merge such a PR?

**Comment by davglass** [comment]
I wouldn't have an issue accepting a PR for that :)

**Comment by hpurmann** [comment]
I just noticed that such a change wouldn't be that easy. `license-checker` is [not recursing further when it sees a module a second time](https://github.com/davglass/license-checker/blob/86772d202b63d4a4c6729b9a774193ca6ef5cb3f/lib/index.js#L37-L43). It makes sense since we already got the license information of that module.

We want the `dependencyPath` to list _all_ modules which have the module as a dependency. The termination condition is having the current module in the list of ancestors.

I guess it's ok to handle these two concerns separately. We will stay with our custom solution of manually calling `read-installed` and recursing over the result.

**Comment by hpurmann** [comment]
We went ahead and wrote [yet another license checker called `advocate`](https://github.com/actano/advocate).

It works with a whitelist and gives the `dependencyPaths` for each module. Returns a map for all modules and one with all violating ones.
