### ISSUE TITLE
A lot of packages are marked as UNKNOWN but have a license in the readme

### ISSUE THREAD

**Issue by hzoo** [davglass/license-checker#76]
It looks like a lot of UNKNOWNs have a MIT license in the readme.

At https://github.com/davglass/license-checker/blob/d7dc3c199636e986b3ba293a67a30bbdfc7bf2b7/lib/index.js#L116-L117 there's a `license(json.readme)` check.

`json.readme` seems to come from `var read = require('read-installed');` which doesn't seem to be maintained/updated anymore (https://github.com/npm/read-package-tree is the new one).

I think there's a bug which results in `ERROR: No README data found!` for the readme.

**Comment by hzoo** [comment]
A horrible way to do this (should be a fix in upstream), but going with https://github.com/hzoo/license-checker/commit/1658b75874df6f4b5a288bc7a2cac8df9daf19d5

**Comment by davglass** [comment]
Can I get an example package that shows the no readme data found error? That way I can add a test for it?

**Comment by hzoo** [comment]
Oh yeah definetely should of did that!

Just trying it out on the project that is using this repo - https://github.com/behance/license-to-fail. I added a console.log inside the check: https://github.com/hzoo/license-checker/commit/1658b75874df6f4b5a288bc7a2cac8df9daf19d5,

<details>
> license-to-fail@1.2.2 check-license /Users/hzhu/dev/license-to-fail
> ./bin/license-to-fail.js ./example-config.js

chalk@0.5.1
ansi-styles@1.1.0
escape-string-regexp@1.0.5
has-ansi@0.1.0
ansi-regex@0.2.1
strip-ansi@0.3.0
supports-color@0.2.0
debug@2.2.0
ms@0.7.1
nopt@2.2.1
abbrev@1.0.9
read-installed@4.0.3
debuglog@1.0.1
read-package-json@2.0.4
glob@6.0.4
inflight@1.0.5
once@1.3.3
wrappy@1.0.2
inherits@2.0.1
minimatch@3.0.3
brace-expansion@1.1.6
balanced-match@0.4.2
path-is-absolute@1.0.0
json-parse-helpfulerror@1.0.3
jju@1.3.0
normalize-package-data@2.3.5
hosted-git-info@2.1.5
is-builtin-module@1.0.0
builtin-modules@1.1.1
semver@5.3.0
validate-npm-package-license@3.0.1
spdx-correct@1.0.2
spdx-license-ids@1.2.2
spdx-expression-parse@1.0.3
readdir-scoped-modules@1.0.2
dezalgo@1.0.3
asap@2.0.4
graceful-fs@4.1.6
slide@1.1.6
util-extend@1.0.3
</detaills>

**Comment by davglass** [comment]
Published in `license-checker@7.0.0`

**Comment by hzoo** [comment]
Awesome! I guess reading the file really is the best way

**Comment by hzoo** [comment]
https://github.com/searls/jasmine-fixture is a weird one: it is also giving UNKNOWN but there is a `LICENSE.txt` with MIT, and it's using the deprecated `licenses` key instead of `license`

**Comment by davglass** [comment]
Published in `license-checker@7.1.0`. Can you open new issues when you find them? I'd rather track them separately than just adding comments in a single issue :)

Thanks

**Comment by hzoo** [comment]
Yep! I wasn't sure
