### ISSUE TITLE
NOTICE files should take priority over LICENSE files.

### ISSUE THREAD

**Issue by graingert** [davglass/license-checker#78]
In the case of Apache 2 you have to include the NOTICE file, not the LICENSE file.  The LICENSE is only shipped for completion.

**Comment by davglass** [comment]
From what I know, IANAL, but a `NOTICE` file is only mandated for Apache Software Foundation projects: http://www.apache.org/dev/licensing-howto.html#overview-of-files

I'm not sure what you want `license-checker` to do with this information. It's only reporting on what's in the repo, nothing more than that. It's looking for LICENSE information, and reporting that to the user. I don't see how adding in the NOTICE file to the output will be of any use.

**Comment by graingert** [comment]
It's recommended, but generally important copyright information goes there. Maybe have a separate property 'notice'?

**Comment by davglass** [comment]
Pushed in `license-checker@8.0.0`
