### ISSUE TITLE
Get full unmodified license text

### ISSUE THREAD

**Issue by dominikhb** [davglass/license-checker#96]
I would like to collect the full license texts of my dependencies. It almost works with the --customPath option and json output.

But the license text is stripped from quotes and line breaks. See lib/index.js:
`moduleInfo.licenseText = content.replace(/"/g, '\'').replace(/\r?\n|\r/g, " ").trim();`

Is there a reason for this? If yes, it might be an idea to add a `moduleInfo.licenseTextOriginal` or similar that contains the unmodified text.

**Comment by davglass** [comment]
IIRC, the `licenseText` was added for exports and it breaks everything but JSON exporting with the carriage returns, new lines and quotes. So they were removed. I'll try to look into a way to add it, but it would likely be easier to just export it to JSON, then write a quick wrapper that walks the JSON and opens the license files if it has a path to one.

**Comment by dominikhb** [comment]
I forgot to say, that I would like to export everything as JSON. Maybe it is an idea to add an export format check into the code and only strip the line breaks and quotes for non-json formats.

**Comment by davglass** [comment]
Published in `license-checker@10.0.0`
